float get_fluid_phi(ivec2 pos)
{
  vec2 xy = vec2(pos) * imageSize(FluidLevelSet).x / consts.width;
  ivec2 ij = ivec2(floor(xy));
  vec2 f = xy - vec2(ij);

  float a = imageLoad(FluidLevelSet, ij + ivec2(0, 0)).x;
  float b = imageLoad(FluidLevelSet, ij + ivec2(1, 0)).x;
  float c = imageLoad(FluidLevelSet, ij + ivec2(0, 1)).x;
  float d = imageLoad(FluidLevelSet, ij + ivec2(1, 1)).x;

  return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}
