name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu_x11:
    name: Build Ubuntu
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build
        run: |
          cmake . -DVORTEX2D_ENABLE_TESTS=On -DVORTEX2D_ENABLE_EXAMPLES=On
          make -j
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

       - name: Cache Vulkan SDK
         id: cache-vulkan-sdk
         uses: actions/cache@v1
         with:
           path: "C:\\VulkanSDK\\1.2.135.0"
           key: vulkan-sdk-1.2.135.0

       - name: Setup Vulkan
         if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
         run: |
             Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.135.0/windows/VulkanSDK-1.2.135.0-Installer.exe" -OutFile VulkanSDK.exe
             $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
             $installer.WaitForExit();

      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          cmake . -DVORTEX2D_ENABLE_TESTS=On -DVORTEX2D_ENABLE_EXAMPLES=On
          cmake --build .